name: haskell-amqp
version: 0.1.0.0
synopsis: AMQP 1.0 client library for Haskell
description: A learning-focused implementation of AMQP 1.0 protocol client
license: MIT
author: pirackr
maintainer: pirackr

dependencies:
  - base >= 4.14 && < 5

library:
  source-dirs: src
  dependencies:
    - binary
    - bytestring
    - text
    - network
    - async
    - stm
    - containers
    - uuid
    - time

tests:
  haskell-amqp-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haskell-amqp
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck
      - bytestring
      - binary
      - time
      - uuid
      - text
